;; -*- lexical-binding: t; -*-

(TeX-add-style-hook
 "triky"
 (lambda ()
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (LaTeX-add-labels
    "chap:triky"
    "sec:coakcemu-trik"
    "sec:trik-efekty"
    "sec:trik-bonus"
    "sec:trik-pridani"
    "sec:trik-vyjimky"
    "sec:trik-rodiny"
    "sec:trik-skladani"
    "sec:trik-vetveni"
    "sec:trik-zakladni"
    "sec:trik-bbz"
    "sec:bbz-jau"
    "sec:bbz-slabiny"
    "sec:trik-bnd"
    "sec:bnd-odstrelovac"
    "sec:bnd-mnohonasobny"
    "sec:trik-bsz"
    "sec:bsz-hruska"
    "sec:bsz-stitar"
    "sec:trik-empatie"
    "sec:empatie-odhalovani"
    "sec:empatie-cit"
    "sec:empatie-terapuet"
    "sec:trik-jezd"
    "sec:jezdectvi-kliste"
    "sec:jezdectvi-hyje"
    "sec:jezdectvi-kamos"
    "sec:trik-klam"
    "sec:klam-lez"
    "sec:klam-mysl"
    "sec:klam-muz"
    "sec:trik-kondice"
    "sec:kondice-zapas"
    "sec:kondice-drsnak"
    "sec:kondice-nezdolny"
    "sec:trik-kontakty"
    "sec:kontakty-drbna"
    "sec:kontakty-ucho"
    "sec:kontakty-reputace"
    "sec:trik-medicina"
    "sec:medicina-ambulance"
    "sec:medicina-vyziva"
    "sec:medicina-boj"
    "sec:trik-mobilita"
    "sec:mobilita-parkour"
    "sec:mobilita-sprinter"
    "sec:mobilita-zmizeni"
    "sec:trik-pozornost"
    "sec:pozornost-ctenar"
    "sec:pozornost-strelba"
    "sec:pozornost-smysl"
    "sec:trik-provokace"
    "sec:provokace-zbroj"
    "sec:provokace-cos"
    "sec:provokace-stourani"
    "sec:trik-remesla"
    "sec:remesla-pripraven"
    "sec:remesla-lepsi"
    "sec:remesla-zbrane"
    "sec:trik-skryvani"
    "sec:skryvani-tvar"
    "sec:skryvani-nejasny"
    "sec:skryvani-zmizel"
    "sec:skryvani-utok"
    "sec:trik-ucenost"
    "sec:ucenost-specialista"
    "sec:ucenost-smysl"
    "sec:ucenost-cetl"
    "sec:trik-vule"
    "sec:vule-nebojsa"
    "sec:vule-duch"
    "sec:vule-ublizit"
    "sec:trik-vysetrovani"
    "sec:vysetrovani-mikro"
    "sec:vysetrovani-fizlovani"
    "sec:vysetrovani-detektiv"
    "vysetrovani-stopovani"
    "sec:trik-vztahy"
    "sec:vztahy-demgagog"
    "sec:vztahy-individual"
    "sec:vztahy-piti"
    "sec:vztahy-popularni"
    "sec:trik-zlodejina"
    "sec:zlodejina-vratka"
    "sec:zlodejina-odbornik"
    "sec:zlodejina-septani"))
 :latex)

